In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('spam.csv')

In [2]:
print(df.head())


  class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  


In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   class       5572 non-null   object
 1   message     5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB
None


In [4]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True) #delete this rows from table

In [7]:
print(df.head())


  class                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


In [38]:
 df['label'] = df['class'].map({'ham': 0, 'spam': 1}) 
X = df['message']
y = df['label'] 

In [39]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will �_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object


In [40]:
print(y)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5572, dtype: int64


In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv = CountVectorizer()         # to extraction data 
X = cv.fit_transform(X)  # Fit the Data    ||  to extraction data 

In [43]:
print(X)

  (0, 3539)	1
  (0, 8006)	1
  (0, 4330)	1
  (0, 5900)	1
  (0, 2321)	1
  (0, 1304)	1
  (0, 5517)	1
  (0, 4074)	1
  (0, 1751)	1
  (0, 3623)	1
  (0, 8463)	1
  (0, 4456)	1
  (0, 1749)	1
  (0, 2044)	1
  (0, 7622)	1
  (0, 3583)	1
  (0, 1070)	1
  (0, 8242)	1
  (1, 5484)	1
  (1, 4492)	1
  (1, 4298)	1
  (1, 8366)	1
  (1, 5513)	1
  (2, 4074)	1
  (2, 3347)	1
  :	:
  (5570, 4204)	1
  (5570, 8288)	1
  (5570, 1085)	1
  (5570, 4596)	1
  (5570, 7018)	1
  (5570, 3298)	1
  (5570, 7604)	1
  (5570, 1438)	1
  (5570, 5316)	1
  (5570, 2586)	1
  (5570, 8041)	1
  (5570, 1778)	1
  (5570, 7028)	1
  (5570, 2883)	1
  (5570, 3459)	1
  (5570, 1786)	1
  (5570, 3676)	1
  (5570, 4148)	1
  (5570, 904)	1
  (5570, 1546)	1
  (5571, 7733)	1
  (5571, 5226)	1
  (5571, 4211)	2
  (5571, 7862)	1
  (5571, 6483)	1


In [44]:
from sklearn.model_selection import train_test_split 

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [46]:
from sklearn.naive_bayes import MultinomialNB

In [49]:
clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

In [50]:
 clf.score(X_train, y_train)

0.99464237878382

In [51]:
clf.score(X_test, y_test)

0.9793365959760739

In [52]:
from sklearn.metrics import classification_report

In [54]:
ypredict = clf.predict(X_train)
print(ypredict)  


[0 0 0 ... 0 0 0]


In [55]:
print ('\nTraining classification report\n', classification_report(y_train, ypredict))


Training classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3238
           1       0.99      0.97      0.98       495

    accuracy                           0.99      3733
   macro avg       0.99      0.99      0.99      3733
weighted avg       0.99      0.99      0.99      3733



In [58]:
ypredict = clf.predict(X_test)
print(ypredict)

[1 0 1 ... 0 0 1]


In [59]:
print ('\nTraining classification report\n', classification_report(y_test, ypredict))


Training classification report
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1587
           1       0.93      0.92      0.92       252

    accuracy                           0.98      1839
   macro avg       0.96      0.95      0.96      1839
weighted avg       0.98      0.98      0.98      1839



In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
ypredict = clf.predict(X_train) 
print ("\n Confusion matrix of training \n", confusion_matrix(y_train, ypredict))


 Confusion matrix of training 
 [[3231    7]
 [  13  482]]


In [62]:
ypredict = clf.predict(X_test) 
print ("\n Confusion matrix of training \n", confusion_matrix(y_test, ypredict))


 Confusion matrix of training 
 [[1569   18]
 [  20  232]]
